apiVersion: v1
kind: ConfigMap
metadata:
  name: users-api-config
  namespace: default
data:
  Jwt__Issuer: "FCGames"
  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__VirtualHost: "/"
  RabbitMQ__Username: "fcg_user"
