apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  namespace: default
  labels:
    app: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
      - name: users-api
        image: igoranthony12/users-api:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: users-api-config
        - secretRef:
            name: users-api-secrets
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
