apiVersion: v1
kind: Secret
metadata:
  name: users-api-secrets
  namespace: default
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=postgres-service;Port=5432;Database=postgres;Username=postgres;Password=root"
  Jwt__Key: "ChaveSuperSecretaECompridaDeExemplo123!"
  RabbitMQ__Password: "guest"
